"""add core models

Revision ID: 1c04d250a5d7
Revises: 
Create Date: 2026-07-10 00:53:54.452771

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '1c04d250a5d7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=150), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('password_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_super_admin', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_user_email'), 'admin_user', ['email'], unique=True)
    op.create_table('category_fee_default',
    sa.Column('category', sa.Enum('school', 'coaching', 'english', 'computer', name='feecategory'), nullable=False),
    sa.Column('default_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.PrimaryKeyConstraint('category')
    )
    op.create_table('class_level',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('class_offset', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_class_level_class_offset'), 'class_level', ['class_offset'], unique=True)
    op.create_table('roll_number_counter',
    sa.Column('cohort_code', sqlmodel.sql.sqltypes.AutoString(length=2), nullable=False),
    sa.Column('last_sequence', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('cohort_code')
    )
    op.create_table('system_setting',
    sa.Column('key', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('value', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('teacher',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('staff_id', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=150), nullable=False),
    sa.Column('qr_code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_teacher_qr_code'), 'teacher', ['qr_code'], unique=True)
    op.create_index(op.f('ix_teacher_staff_id'), 'teacher', ['staff_id'], unique=True)
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.Enum('create', 'update', 'delete', name='auditaction'), nullable=False),
    sa.Column('entity_type', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('before_value', sa.JSON(), nullable=True),
    sa.Column('after_value', sa.JSON(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['admin_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_log_admin_id'), 'audit_log', ['admin_id'], unique=False)
    op.create_index(op.f('ix_audit_log_entity_id'), 'audit_log', ['entity_id'], unique=False)
    op.create_index(op.f('ix_audit_log_entity_type'), 'audit_log', ['entity_type'], unique=False)
    op.create_index(op.f('ix_audit_log_timestamp'), 'audit_log', ['timestamp'], unique=False)
    op.create_table('student',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('roll_number', sqlmodel.sql.sqltypes.AutoString(length=5), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=150), nullable=False),
    sa.Column('father_name', sqlmodel.sql.sqltypes.AutoString(length=150), nullable=False),
    sa.Column('parent_whatsapp', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('qr_code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('class_level_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['class_level_id'], ['class_level.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_student_class_level_id'), 'student', ['class_level_id'], unique=False)
    op.create_index(op.f('ix_student_qr_code'), 'student', ['qr_code'], unique=True)
    op.create_index(op.f('ix_student_roll_number'), 'student', ['roll_number'], unique=True)
    op.create_table('attendance_record',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('teacher_id', sa.Integer(), nullable=True),
    sa.Column('scan_date', sa.Date(), nullable=False),
    sa.Column('arrival_time', sa.Time(), nullable=False),
    sa.Column('punctuality_status', sa.Enum('on_time', 'late', name='punctualitystatus'), nullable=False),
    sa.CheckConstraint('(student_id IS NOT NULL AND teacher_id IS NULL) OR (student_id IS NULL AND teacher_id IS NOT NULL)', name='ck_attendance_exactly_one_owner'),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['teacher.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attendance_record_scan_date'), 'attendance_record', ['scan_date'], unique=False)
    op.create_index(op.f('ix_attendance_record_student_id'), 'attendance_record', ['student_id'], unique=False)
    op.create_index(op.f('ix_attendance_record_teacher_id'), 'attendance_record', ['teacher_id'], unique=False)
    op.create_table('enrollment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.Enum('school', 'coaching', 'english', 'computer', name='feecategory'), nullable=False),
    sa.Column('discount_type', sa.Enum('none', 'fixed', 'percentage', name='discounttype'), nullable=False),
    sa.Column('discount_value', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('status', sa.Enum('active', 'inactive', name='enrollmentstatus'), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['category'], ['category_fee_default.category'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['admin_user.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ),
    sa.ForeignKeyConstraint(['updated_by_id'], ['admin_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_enrollment_category'), 'enrollment', ['category'], unique=False)
    op.create_index('ix_enrollment_one_active_per_student_category', 'enrollment', ['student_id', 'category'], unique=True, postgresql_where=sa.text("status = 'active'"))
    op.create_index(op.f('ix_enrollment_status'), 'enrollment', ['status'], unique=False)
    op.create_index(op.f('ix_enrollment_student_id'), 'enrollment', ['student_id'], unique=False)
    op.create_table('fee_cycle',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('period', sqlmodel.sql.sqltypes.AutoString(length=7), nullable=False),
    sa.Column('total_due', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.Enum('unpaid', 'paid', name='feecyclestatus'), nullable=False),
    sa.Column('paid_date', sa.Date(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['admin_user.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ),
    sa.ForeignKeyConstraint(['updated_by_id'], ['admin_user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'period', name='uq_fee_cycle_student_period')
    )
    op.create_index(op.f('ix_fee_cycle_status'), 'fee_cycle', ['status'], unique=False)
    op.create_index(op.f('ix_fee_cycle_student_id'), 'fee_cycle', ['student_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fee_cycle_student_id'), table_name='fee_cycle')
    op.drop_index(op.f('ix_fee_cycle_status'), table_name='fee_cycle')
    op.drop_table('fee_cycle')
    op.drop_index(op.f('ix_enrollment_student_id'), table_name='enrollment')
    op.drop_index(op.f('ix_enrollment_status'), table_name='enrollment')
    op.drop_index('ix_enrollment_one_active_per_student_category', table_name='enrollment', postgresql_where=sa.text("status = 'active'"))
    op.drop_index(op.f('ix_enrollment_category'), table_name='enrollment')
    op.drop_table('enrollment')
    op.drop_index(op.f('ix_attendance_record_teacher_id'), table_name='attendance_record')
    op.drop_index(op.f('ix_attendance_record_student_id'), table_name='attendance_record')
    op.drop_index(op.f('ix_attendance_record_scan_date'), table_name='attendance_record')
    op.drop_table('attendance_record')
    op.drop_index(op.f('ix_student_roll_number'), table_name='student')
    op.drop_index(op.f('ix_student_qr_code'), table_name='student')
    op.drop_index(op.f('ix_student_class_level_id'), table_name='student')
    op.drop_table('student')
    op.drop_index(op.f('ix_audit_log_timestamp'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_entity_type'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_entity_id'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_admin_id'), table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_index(op.f('ix_teacher_staff_id'), table_name='teacher')
    op.drop_index(op.f('ix_teacher_qr_code'), table_name='teacher')
    op.drop_table('teacher')
    op.drop_table('system_setting')
    op.drop_table('roll_number_counter')
    op.drop_index(op.f('ix_class_level_class_offset'), table_name='class_level')
    op.drop_table('class_level')
    op.drop_table('category_fee_default')
    op.drop_index(op.f('ix_admin_user_email'), table_name='admin_user')
    op.drop_table('admin_user')
    # ### end Alembic commands ###
